Repository erda-project/erda-infra, pull requests merged in 2021-11, with the labels that each got.

#123 support temp state & InParams helper
  providers/component-protocol/cptype/const.go
  providers/component-protocol/cptype/protocol.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/protocol.service.go
  providers/component-protocol/protocol/render.go
Labels: enhancement, approved

#124 support footer in structure
  providers/component-protocol/protocol/render.go
  providers/component-protocol/protocol/render_test.go
Labels: enhancement, approved

#125 feature: mysql-provider support debug mode
  providers/mysql/examples/examples.yaml
  providers/mysql/examples/main.go
  providers/mysql/mysql.go
Labels: enhancement, approved

#126 router configurable
  providers/prometheus/provider.go
Labels: approved

#127 fix: typo in mysql-provider
  providers/mysql/examples/examples.yaml
  providers/mysql/mysql.go
Labels: enhancement, approved

#130 fix: cp default rendering recursive get sub comps
  providers/component-protocol/protocol/component.go
  providers/component-protocol/protocol/render.go
  providers/component-protocol/protocol/render_test.go
Labels: enhancement

#131 fix calculate children hierarchy
  providers/component-protocol/protocol/render.go
  providers/component-protocol/protocol/render_test.go
Labels: approved

#132 component-protocol: add syncIntervalSecond
  providers/component-protocol/cptype/protocol.go
  providers/component-protocol/protobuf/proto-go/Makefile
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.form.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.http.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.json.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.validator.pb.go
  providers/component-protocol/protobuf/proto/cp/protocol.proto
  providers/component-protocol/utils/cputil/obj_test.go
Labels: enhancement, approved

#133 cp: add yaml tag for protocol options
  providers/component-protocol/cptype/protocol.go
Labels: documentation
