Repository erda-project/erda-infra, pull requests merged in 2021-08, with the labels that each got.

#70 upgrade gocql to fix reconnection
  go.mod
  go.sum
Labels: approved

#73 Optimize Kafka producer
  go.mod
  pkg/math/math.go
  pkg/math/math_test.go
  providers/kafka/producer.go
Labels: approved

#75 fix typo in PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved

#74 feature: move strutil pkg from erda to infra
  pkg/strutil/interface.go
  pkg/strutil/interface_test.go
  pkg/strutil/namestyle.go
  pkg/strutil/namestyle_test.go
  pkg/strutil/regexp.go
  pkg/strutil/regexp_test.go
  pkg/strutil/strutil.go
  pkg/strutil/strutil_test.go
  pkg/strutil/validator.go
  pkg/strutil/validator_test.go
Labels: enhancement, approved

#77 Fix: multiple leaders exists after ectd was restarted
  .github/workflows/ci-it.yml
  providers/etcd-election/.gitignore
  providers/etcd-election/election.go
  providers/etcd-election/election_test.go
Labels: approved

#76 fix: i18n provider sprintf escape method get param key correctly
  providers/i18n/examples/hello.yaml
  providers/i18n/examples/main.go
  providers/i18n/provider.go
Labels: approved, bugfix

#80 servicehub provider context return label
  base/servicehub/provider.go
  base/servicehub/provider_context.go
Labels: enhancement, approved

#81 polish servicehub
  base/servicehub/examples/dependency-multi/main.go
  base/servicehub/hub.go
  go.mod
  go.sum
Labels: enhancement

#87 infra: enhance ProviderContext interface; polish component-protcol provider
  base/servicehub/provider.go
  base/servicehub/provider_context.go
  go.mod
  go.sum
  providers/component-protocol/examples/components/demotable/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/protocol/component.go
  providers/component-protocol/provider.go
  providers/component-protocol/utils/cputil/sdk.go
Labels: enhancement
