Repository erda-project/erda-infra, pull requests merged in 2021-12, with the labels that each got.

#138 bugfix: fix stream api generated error
  tools/protoc/protoc-gen-go-client/client.go
  tools/protoc/protoc-gen-go-client/provider.go
Labels: bugfix

#141 cp: remove useless UniversalStructuredCompPtr
  providers/component-protocol/components/kanban/impl/default.go
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/examples/scenarios/kanban-demo.yml
  providers/component-protocol/protocol/framework.go
  providers/component-protocol/protocol/render.go
Labels: enhancement

#143 cp: operation add skipRender option
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/utils/cputil/operation_builder.go
Labels: enhancement

#142 cp: split IDefaultComponent from IComponent
  providers/component-protocol/cptype/component.go
  providers/component-protocol/cptype/component_default.go
Labels: enhancement, approved

#144 cp: defaultKanban implement visible default to true
  providers/component-protocol/components/kanban/impl/default.go
Labels: enhancement, approved

#146 feature: TopN component
  providers/component-protocol/components/topn/impl/decoder.go
  providers/component-protocol/components/topn/impl/default.go
  providers/component-protocol/components/topn/impl/encoder.go
  providers/component-protocol/components/topn/interface.go
  providers/component-protocol/components/topn/model.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/top_demo/top/init.go
  providers/component-protocol/examples/components/top_demo/top/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/scenarios/top-demo.yml
Labels: enhancement, approved

#148 Update component configurable filter model
  providers/component-protocol/components/filter/custom.go
  providers/component-protocol/components/filter/impl/decoder.go
  providers/component-protocol/components/filter/impl/default.go
  providers/component-protocol/components/filter/impl/encoder.go
  providers/component-protocol/components/filter/model.go
  providers/component-protocol/components/filter/models/condition.go
  providers/component-protocol/components/filter/models/option.go
  providers/component-protocol/examples/components/filter_demo/filter/provider.go
Labels: approved

#150 feature: cp comp instance support register non-std operations
  providers/component-protocol/components/filter/impl/default.go
  providers/component-protocol/components/kanban/impl/default.go
  providers/component-protocol/components/topn/impl/default.go
  providers/component-protocol/cptype/component.go
  providers/component-protocol/cptype/component_default.go
  providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
  providers/component-protocol/protocol/framework.go
Labels: enhancement

#147 cp: add basic list component
  providers/component-protocol/components/list/custom.go
  providers/component-protocol/components/list/impl/decoder.go
  providers/component-protocol/components/list/impl/default.go
  providers/component-protocol/components/list/impl/encoder.go
  providers/component-protocol/components/list/interface.go
  providers/component-protocol/components/list/model.go
  providers/component-protocol/components/list/model_test.go
  providers/component-protocol/components/list/operation.go
Labels: approved

#151 feat(component-protocol): add component cardlist
  providers/component-protocol/components/cardlist/custom.go
  providers/component-protocol/components/cardlist/impl/decoder.go
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/cardlist/impl/encoder.go
  providers/component-protocol/components/cardlist/interface.go
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/components/cardlist/models/textInfo.go
  providers/component-protocol/components/cardlist/operation.go
Labels: approved

#153 refactor(cp): change fields and add star operation
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/cardlist/interface.go
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/components/cardlist/models/textInfo.go
  providers/component-protocol/components/cardlist/operation.go
Labels: approved

#154 refactor(cp): change textinfo to textmeta
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/components/cardlist/models/textInfo.go
Labels: approved

#155 Featuer/list update
  providers/component-protocol/components/list/impl/default.go
  providers/component-protocol/components/list/interface.go
  providers/component-protocol/components/list/model.go
  providers/component-protocol/components/list/operation.go
Labels: approved

#156 add std operations
  providers/component-protocol/components/list/impl/default.go
  providers/component-protocol/components/list/interface.go
  providers/component-protocol/components/list/model.go
  providers/component-protocol/components/list/operation.go
Labels: approved

#158 refactor(cp): card list
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/components/cardlist/models/textInfo.go
Labels: approved

#159 refactor(cp): card list
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/cardlist/interface.go
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/components/cardlist/operation.go
Labels: approved

#157 add tip field to operation
  providers/component-protocol/components/cardlist/model.go
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/utils/cputil/operation_builder.go
Labels: approved

#160 Add filter operations definition in data
  providers/component-protocol/components/filter/model.go
  providers/component-protocol/examples/components/filter_demo/filter/provider.go
  providers/component-protocol/protocol/component.go
  providers/component-protocol/protocol/register.go
Labels: approved

#162 Cp card
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/cardlist/interface.go
  providers/component-protocol/components/cardlist/model.go
Labels: approved

#163 message list, need client data when click
  providers/component-protocol/components/list/operation.go
Labels: approved

#164 fix: cp opServerData do not wrap `extra` key
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/utils/cputil/operation_builder.go
Labels: bugfix

#165 cp: proto comp add version field
  providers/component-protocol/protobuf/proto-go/cp/client/provider.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.form.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.pb.go
  providers/component-protocol/protobuf/proto/cp/protocol.proto
Labels: feature

#166 update list star to point
  providers/component-protocol/components/list/model.go
Labels: approved

#168 fix arm system panic
  pkg/trace/inject/context/context.go
Labels: approved

#169 refactor(cp): remove cards json tag
  providers/component-protocol/components/cardlist/model.go
Labels: approved

#170 set main state to point
  providers/component-protocol/components/list/model.go
Labels: approved

#172 feature: support line graph
  providers/component-protocol/components/linegraph/impl/decoder.go
  providers/component-protocol/components/linegraph/impl/default.go
  providers/component-protocol/components/linegraph/impl/encoder.go
  providers/component-protocol/components/linegraph/interface.go
  providers/component-protocol/components/linegraph/model.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/scenarios/linegraph-demo.yml
Labels: enhancement, approved

#174 cp: fix component unmarshal omitempty issue
  providers/component-protocol/protocol/framework.go
Labels: bugfix

#177 chore: add semantic.yml for pr title check
  .github/semantic.yml
Labels: approved

#178 chore: remove useless type of pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved

#176 feat: support kv component
  providers/component-protocol/components/kv/impl/decoder.go
  providers/component-protocol/components/kv/impl/default.go
  providers/component-protocol/components/kv/impl/encoder.go
  providers/component-protocol/components/kv/interface.go
  providers/component-protocol/components/kv/model.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/kv_demo/kv/init.go
  providers/component-protocol/examples/components/kv_demo/kv/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/scenarios/kv-demo.yml
Labels: enhancement, approved

#171 feat: support custom&in-cluster config
  providers/kubernetes/examples/examples.yaml
  providers/kubernetes/examples/main.go
  providers/kubernetes/kubernetes.go
Labels: approved

#180 feat: defined customData for kv,topn,linegraph components
  providers/component-protocol/components/kv/custom.go
  providers/component-protocol/components/kv/impl/decoder.go
  providers/component-protocol/components/kv/impl/encoder.go
  providers/component-protocol/components/linegraph/custom.go
  providers/component-protocol/components/linegraph/impl/decoder.go
  providers/component-protocol/components/linegraph/impl/encoder.go
  providers/component-protocol/components/topn/custom.go
  providers/component-protocol/components/topn/impl/decoder.go
  providers/component-protocol/components/topn/impl/encoder.go
Labels: enhancement, approved

#179 feat: Add fix property in filter option base
  .gitignore
  providers/component-protocol/components/filter/models/option.go
  providers/component-protocol/examples/components/filter_demo/filter/provider.go
Labels: approved

#181 feat: add sorter field for Table
  providers/component-protocol/components/table/model.go
Labels: enhancement, approved

#182 fix: fix table operation
  providers/component-protocol/components/table/operation.go
Labels: enhancement, approved

#185 update go mod
  tools/go.mod
  tools/go.sum
Labels: approved

#184 feat: add subTitle field for linegraph
  providers/component-protocol/components/linegraph/model.go
Labels: enhancement, approved
