Repository erda-project/erda-infra, pull requests merged in 2021-09, with the labels that each got.

#90 forward remote request to local
  go.mod
  go.sum
  providers/component-protocol/protocol/register.go
  providers/remote-forward/client/examples/examples.yaml
  providers/remote-forward/client/examples/main.go
  providers/remote-forward/client/provider.go
  providers/remote-forward/connect.go
  providers/remote-forward/protocol.go
  providers/remote-forward/protocol_test.go
  providers/remote-forward/server/examples/examples.yaml
  providers/remote-forward/server/examples/main.go
  providers/remote-forward/server/provider.go
Labels: approved

#91 http encode support bytes type & fix dependency issue
  base/servicehub/config.go
  pkg/transport/http/encoding/encoding.go
  pkg/transport/http/encoding/encoding_test.go
Labels: enhancement, approved, bugfix

#92 1、fix encoding for ContentLength、fix Interceptor order
  pkg/transport/http/encoding/encoding.go
  pkg/transport/http/handle.go
  providers/all.go
Labels: approved

#93 fix etcd mutex
  providers/etcd-mutex/examples/main.go
  providers/etcd-mutex/mutex.go
Labels: approved

#94 fix i18n bug
  providers/i18n/examples/main.go
  providers/i18n/provider.go
Labels: approved

#97 fix mismatch of interface and implementation of grpcclient
  pkg/transport/http/handle.go
  providers/grpcclient/provider.go
Labels: approved

#98 add X-Need-User-Info header in response
  go.mod
  providers/component-protocol/provider.go
  providers/component-protocol/provider_test.go
Labels: approved

#99 etcd-election add resign log & remove temp data dir
  providers/etcd-election/election.go
  providers/etcd-election/election_test.go
Labels: enhancement, approved

#102 add error encoder
  providers/component-protocol/provider.go
  providers/component-protocol/provider_test.go
Labels: approved
