Repository erda-project/erda-infra, pull requests merged in 2022-05, with the labels that each got.

#269 fix: Fix cp option visible can not be set to false.
  .github/PULL_REQUEST_TEMPLATE.md
  providers/component-protocol/protocol/posthook/simplify.go
  providers/component-protocol/protocol/posthook/simplify_test.go
Labels: approved, bugfix

#270 feat: hub content config support env escape as file
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, feature

#271 feat: add RegisterTextFromFS function to i18 provider
  providers/i18n/examples/i18n/common/hello.yaml
  providers/i18n/examples/i18n/files/hello.yaml
  providers/i18n/examples/main.go
  providers/i18n/provider.go
  providers/i18n/register.go
  providers/i18n/register_test.go
Labels: approved, feature

#273 fix: use file data register i18n file to provider
  providers/i18n/register.go
Labels: approved, bugfix

#274 feat: support readable config for ck
  providers/clickhouse/clickhouse.go
  providers/clickhouse/examples/examples.yaml
Labels: approved, feature

#276 polish: git clone set depth to 1
  tools/gohub/cmd/tools/install/install.go
Labels: approved

#277 feature: add ghproxy&goproxy for gohub tools install
  tools/gohub/cmd/tools/install/cmd.go
  tools/gohub/cmd/tools/install/install.go
Labels: approved

#280 feat: limit max wait time for kafka to avoid long time block on slow …
  providers/kafka/batch_reader.go
Labels: approved
