Repository erda-project/erda-infra, pull requests merged in 2022-02, with the labels that each got.

#234 fix: Add mysql charset client config
  providers/mysql/examples/examples.yaml
  providers/mysql/mysql.go
Labels: bugfix

#236 fix: cp: add ReturnAllComponents options
  providers/component-protocol/cptype/protocol.go
  providers/component-protocol/protocol/render.go
Labels: approved, bugfix

#237 fix: move ReturnAllComponents option check into func OnlyReturnRenderingComps
  providers/component-protocol/protocol/posthook/only_return_rendering.go
  providers/component-protocol/protocol/render.go
Labels: approved, bugfix

#238 fix: trace go run
  pkg/parallel/future.go
  pkg/trace/trace.go
Labels: approved, bugfix

#241 fix: add Custom type comp
  providers/component-protocol/protocol/scenario.go
Labels: approved, bugfix

#242 feat: cp add simplify-protocol posthook
  providers/component-protocol/protocol/posthook/simplify.go
  providers/component-protocol/protocol/posthook/simplify_test.go
  providers/component-protocol/protocol/render.go
Labels: approved, feature

#243 refactor(cp-list): change list serverData from string to struct
  providers/component-protocol/components/list/operation.go
Labels: approved

#244 fix: parseParallelRendering subComp is nil
  providers/component-protocol/protocol/render_parallel.go
Labels: approved, bugfix

#246 feat: etcd-election support NonVoter
  providers/etcd-election/election.go
Labels: approved, feature

#247 feat: logger use provider key as module name to distinguish multiple provider instances
  base/servicehub/provider_context.go
Labels: approved, feature
