Repository erda-project/erda-infra, pull requests merged in 2022-01, with the labels that each got.

#183 feat: cp support components parallel rendering
  providers/component-protocol/components/list/model_test.go
  providers/component-protocol/cptype/protocol.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/parallel_demo/chart/provider.go
  providers/component-protocol/examples/components/parallel_demo/filter/provider.go
  providers/component-protocol/examples/components/parallel_demo/grid/provider.go
  providers/component-protocol/examples/components/parallel_demo/topn/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/scenarios/parallel-demo.yml
  providers/component-protocol/examples/scenarios/table-demo.yml
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.pb.go
  providers/component-protocol/protobuf/proto-go/cp/pb/protocol.validator.pb.go
  providers/component-protocol/protobuf/proto/cp/protocol.proto
  providers/component-protocol/protocol/framework.go
  providers/component-protocol/protocol/render.go
  providers/component-protocol/protocol/render_parallel.go
  providers/component-protocol/protocol/render_parallel_test.go
  providers/component-protocol/utils/cputil/obj_test.go
Labels: feature

#187 feat: bubble graph component
  providers/component-protocol/components/bubblegraph/custom.go
  providers/component-protocol/components/bubblegraph/impl/decoder.go
  providers/component-protocol/components/bubblegraph/impl/default.go
  providers/component-protocol/components/bubblegraph/impl/encoder.go
  providers/component-protocol/components/bubblegraph/interface.go
  providers/component-protocol/components/bubblegraph/model.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/bubblegraph_demo/bubblegraph/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/scenarios/bubblegraph-demo.yml
Labels: enhancement, approved

#188 feat: add demo usage for cp custom type
  providers/component-protocol/examples/components/kanban_demo/kanban/custom_type.go
  providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
Labels: feature

#189 fix: parallel rending bugfix, ignore non exist component when do custom rending
  providers/component-protocol/protocol/render_parallel.go
Labels: approved

#191 feat: table custom
  providers/component-protocol/components/table/custom.go
  providers/component-protocol/components/table/impl/decoder.go
  providers/component-protocol/components/table/impl/encoder.go
Labels: enhancement, approved

#192 feat: support copytext cell
  providers/component-protocol/components/commodel/text.go
  providers/component-protocol/components/table/cell_builder.go
Labels: enhancement, approved

#193 feat: cp: support component-level continue render
  providers/component-protocol/cptype/protocol.go
  providers/component-protocol/protocol/posthook/continue_render.go
  providers/component-protocol/protocol/posthook/continue_render_test.go
  providers/component-protocol/protocol/posthook/only_return_rendering.go
  providers/component-protocol/protocol/posthook/only_return_rendering_test.go
  providers/component-protocol/protocol/render.go
Labels: feature

#195 refactor(cp): delete key for moreOp in component list
  providers/component-protocol/components/list/model.go
Labels: approved

#196 feat: cp: table support moreOperations
  providers/component-protocol/components/commodel/click.go
  providers/component-protocol/components/commodel/moreoperations.go
  providers/component-protocol/components/table/cell_builder.go
  providers/component-protocol/examples/components/table_demo/table/provider.go
Labels: feature

#197 feat: table click add missing serverData&clientData
  providers/component-protocol/components/commodel/moreoperations.go
  providers/component-protocol/examples/components/table_demo/table/provider.go
Labels: feature

#198 feat: revert cp onlyReturnRendering temporarily
  providers/component-protocol/protocol/render.go
Labels: feature

#199 feat: support hide save filter & add status to text
  providers/component-protocol/components/commodel/text.go
  providers/component-protocol/components/filter/model.go
Labels: approved, feature

#200 fix: update the status type of text model
  providers/component-protocol/components/commodel/status.go
Labels: approved

#201 fix: fix the bug of user cell
  providers/component-protocol/components/table/cell_builder.go
Labels: approved

#202 feat: table column support hidden
  providers/component-protocol/components/table/model.go
Labels: feature

#203 feat: linegraph and bubblegraph auto unit
  providers/component-protocol/components/bubblegraph/model.go
  providers/component-protocol/components/bubblegraph/readme.md
  providers/component-protocol/components/commodel/data-structure/data_structure.go
  providers/component-protocol/components/linegraph/model.go
  providers/component-protocol/components/linegraph/readme.md
  providers/component-protocol/examples/components/bubblegraph_demo/bubblegraph/provider.go
  providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
Labels: enhancement, approved

#204 feat: cp: component register decouple from servicehub-provider
  providers/component-protocol/cpregister/register_comp.go
  providers/component-protocol/examples/components/kanban_demo/kanban.http
  providers/component-protocol/examples/components/kanban_demo/kanban/custom_type.go
  providers/component-protocol/examples/components/kanban_demo/kanban/init.go
  providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/examples/i18n/scenarios/notbelong.yaml
Labels: feature

#206 feat: cp: optionally register component as provider
  providers/component-protocol/cpregister/base/comp_register.go
  providers/component-protocol/cpregister/register_comp_provider.go
  providers/component-protocol/examples/components/kanban_demo/kanban/init.go
  providers/component-protocol/examples/demo.yaml
  providers/component-protocol/utils/cputil/provider_name.go
  providers/component-protocol/utils/cputil/provider_name_test.go
Labels: feature

#208 feat: defined type
  providers/component-protocol/components/commodel/data-structure/data_structure.go
Labels: enhancement, approved

#207 feat: cp: add EnhancedOperationFunc with std-response to resolve provider-comp's concurrency-issue
  providers/component-protocol/components/bubblegraph/impl/default.go
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/defaults/default.go
  providers/component-protocol/components/filter/impl/default.go
  providers/component-protocol/components/kanban/impl/default.go
  providers/component-protocol/components/kv/impl/default.go
  providers/component-protocol/components/linegraph/impl/default.go
  providers/component-protocol/components/list/impl/default.go
  providers/component-protocol/components/table/impl/default.go
  providers/component-protocol/components/topn/impl/default.go
  providers/component-protocol/cpregister/register_comp.go
  providers/component-protocol/cptype/component.go
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/paralleldemo/comp.go
  providers/component-protocol/examples/components/paralleldemo/test.http
  providers/component-protocol/examples/scenarios/parallel-demo.yml
  providers/component-protocol/protocol/framework.go
Labels: feature, component-protocol

#209 feat: add disabled to filter condition
  providers/component-protocol/components/filter/models/condition.go
Labels: approved

#210 fix: fix the nil pointer problem with base init
  providers/component-protocol/cpregister/base/comp_register.go
Labels: approved

#211 fix: compatible with old register methods
  providers/component-protocol/components/defaults/default.go
Labels: approved

#212 refactor: cp: let EnhancedOperationFunc become OperationFunc
  providers/component-protocol/components/cardlist/impl/default.go
  providers/component-protocol/components/defaults/default.go
  providers/component-protocol/components/filter/impl/default.go
  providers/component-protocol/components/kanban/impl/default.go
  providers/component-protocol/components/list/impl/default.go
  providers/component-protocol/components/table/impl/default.go
  providers/component-protocol/cptype/component.go
  providers/component-protocol/cptype/operation.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/examples/components/bubblegraph_demo/bubblegraph/provider.go
  providers/component-protocol/examples/components/filter_demo/filter/provider.go
  providers/component-protocol/examples/components/kanban_demo/kanban/provider.go
  providers/component-protocol/examples/components/kv_demo/kv/provider.go
  providers/component-protocol/examples/components/linegraph_demo/linegraph/provider.go
  providers/component-protocol/examples/components/paralleldemo/comp.go
  providers/component-protocol/examples/components/table_demo/table/provider.go
  providers/component-protocol/examples/components/top_demo/top/provider.go
  providers/component-protocol/protocol/framework.go
Labels: component-protocol, refactor

#213 fix(cp): change selectable to pointer
  providers/component-protocol/components/list/model.go
Labels: approved

#214 feat: options enable
  providers/component-protocol/components/bubblegraph/model.go
  providers/component-protocol/components/linegraph/model.go
Labels: approved

#216 refactor(cp): change logourl to icon
  providers/component-protocol/components/list/model.go
Labels: approved

#215 feat: Component protocol default protocol yml support i18n
  providers/component-protocol/examples/i18n/scenarios/filter-demo.yaml
  providers/component-protocol/examples/scenarios/filter-demo.yml
  providers/component-protocol/protocol/i18n.go
  providers/component-protocol/protocol/protocol.go
Labels: approved

#218 feat: add duration cellType
  providers/component-protocol/components/commodel/duration.go
  providers/component-protocol/components/table/cell_builder.go
Labels: approved, feature, component-protocol

#219 fix: fix the bug of icon cell
  providers/component-protocol/components/commodel/duration.go
  providers/component-protocol/components/table/cell_builder.go
Labels: approved, bugfix, component-protocol

#217 feat: cp table add progressBar cellType
  providers/component-protocol/components/commodel/progress_bar.go
  providers/component-protocol/components/table/cell_builder.go
  providers/component-protocol/examples/components/table_demo/table/provider.go
Labels: feature, component-protocol

#224 cp: reopen onlyReturnRendering
  providers/component-protocol/protocol/render.go
Labels: feature, component-protocol

#226 feat: cp global options add EnableWebSocket switch (default: false)
  providers/component-protocol/cptype/protocol.go
Labels: feature, component-protocol

#221 fix: cp sdk clone inParams&globalStates
  go.mod
  go.sum
  providers/component-protocol/cpregister/register_comp_provider.go
  providers/component-protocol/cpregister/register_comp_provider_test.go
  providers/component-protocol/cptype/sdk.go
  providers/component-protocol/cptype/sdk_test.go
  providers/component-protocol/protocol/framework.go
Labels: bugfix, component-protocol

#220 fix: cp render posthook for parallel
  providers/component-protocol/examples/components/paralleldemo/comp.go
  providers/component-protocol/examples/components/paralleldemo/test.http
  providers/component-protocol/protocol/render.go
Labels: bugfix, component-protocol

#227 feat: complex graph component
  providers/component-protocol/components/complexgraph/custom.go
  providers/component-protocol/components/complexgraph/impl/decoder.go
  providers/component-protocol/components/complexgraph/impl/default.go
  providers/component-protocol/components/complexgraph/impl/encoder.go
  providers/component-protocol/components/complexgraph/interface.go
  providers/component-protocol/components/complexgraph/model.go
  providers/component-protocol/components/complexgraph/readme.md
  providers/component-protocol/examples/components/all.go
  providers/component-protocol/examples/components/complexgraph_demo/complexgraph/provider.go
  providers/component-protocol/examples/scenarios/complexgraph-demo.yml
Labels: approved, feature

#228 feat(component-protocol): add WebSocketEventType
  providers/component-protocol/cptype/websocket.go
Labels: feature, component-protocol

#229 feat: Component protocol set visible after operation handle
  providers/component-protocol/protocol/framework.go
Labels: approved, feature

#230 feat: support traced go routine
  pkg/parallel/future.go
  pkg/parallel/future_test.go
  pkg/parallel/group.go
  pkg/parallel/group_test.go
  pkg/trace/trace.go
Labels: approved, feature

#231 fix:Fix simplify comp default visible option
  providers/component-protocol/protocol/render.go
Labels: bugfix

#232 feat: Filter support expose condition, add input type condition constructor
  providers/component-protocol/components/filter/models/condition.go
  providers/component-protocol/examples/components/filter_demo/filter/provider.go
Labels: feature

#233 fix: Merge component global state after finalize
  providers/component-protocol/protocol/framework.go
Labels: bugfix
