Repository erda-project/erda-infra, pull requests merged in 2022-03, with the labels that each got.

#248 feat: Get component from default protocol if not exist
  providers/component-protocol/examples/scenarios/filter-demo.yml
  providers/component-protocol/protocol/protocol.go
Labels: approved, feature

#250 feat(component-protocol): slot rendering order takes precedence
  providers/component-protocol/protocol/render.go
  providers/component-protocol/protocol/render_test.go
Labels: approved, feature, component-protocol

#252 feat: add clickhouse client provider
  go.mod
  go.sum
  providers/all.go
  providers/clickhouse/clickhouse.go
  providers/clickhouse/examples/examples.yaml
  providers/clickhouse/examples/main.go
Labels: feature

#253 feature: mysql client support tls setting
  providers/mysql/examples/examples.yaml
  providers/mysql/mysql.go
Labels: feature

#255 feat: add gorm.v2
  go.mod
  go.sum
  providers/mysql/v2/mysql.go
  providers/mysql/v2/plugins/fields/soft_delete.go
  providers/mysql/v2/plugins/fields/soft_delete_test.go
  providers/mysql/v2/plugins/fields/uuid.go
  providers/mysql/v2/plugins/fields/uuid_test.go
  tools/gohub/cmd/protoc/protoc.go
Labels: feature

#254 feat: Database connection increases tls configuration
  go.mod
  go.sum
  pkg/mysqldriver/tls.go
  pkg/mysqldriver/tls_test.go
  providers/mysql/mysql.go
  providers/mysql/mysql_test.go
  providers/mysql/v2/mysql.go
  providers/mysqlxorm/xorm.go
  providers/mysqlxorm/xorm_test.go
Labels: feature

#258 feat: autowired support inherit-label
  base/servicehub/examples/dependency-autowired/examples.yaml
  base/servicehub/examples/dependency-autowired/main.go
  base/servicehub/hub.go
  base/servicehub/provider_context.go
Labels: enhancement, approved, feature

#259 feat: servicehub print signal when quit
  base/servicehub/hub.go
Labels: feature

#260 feat: add safe pkg to recover from goroutine panic
  pkg/safe/goroutine.go
  pkg/safe/goroutine_test.go
Labels: feature

#262 chore: enlarge mysql max open/idle connections for v2
  providers/mysql/v2/mysql.go
Labels: approved
