Repository erda-project/erda-infra, pull requests merged in 2022-04, with the labels that each got.

#263 feat: config support "|" operator
  base/servicehub/config.go
  base/servicehub/hub.go
  base/servicehub/provider_context.go
  go.mod
  pkg/config/config.go
  pkg/config/config_test.go
  providers/component-protocol/protocol/translator/translator.go
  providers/i18n/provider.go
Labels: approved, feature

#265 fix: golangci-lint issue of go 1.18
  .github/workflows/ci-it.yml
Labels: bugfix

#264 feat: add dump stack for safe pkg
  pkg/safe/goroutine.go
Labels: feature

#266 feat: support batch size bytes limit
  providers/cassandra/cassandra.go
  providers/cassandra/writer.go
Labels: feature

#268 feat: allows to skip go-form
  tools/protoc/protoc-gen-go-form/form.go
Labels: feature
