Repository erda-project/erda-infra, pull requests merged in 2022-08, with the labels that each got.

#291 feat: add path vars to request context
  providers/httpserver/path.go
  providers/httpserver/path_test.go
Labels: feature

#293 chore: fix golangci lint
  Makefile
  pkg/strutil/strutil.go
  pkg/trace/inject/http-client/http_client.go
  pkg/transport/http/encoding/jsonpb/encode.go
  pkg/transport/http/httprule/parse.go
  providers/component-protocol/components/commodel/data-structure/data_structure.go
  providers/component-protocol/protocol/event.go
  providers/component-protocol/protocol/translator/translator.go
Labels: approved

#292 chore: httpserver remove recover interceptor to avoid always statuscode 200
  providers/httpserver/provider.go
Labels: approved

#295 chore: comment out mysql v2 problematic unit tests temporarily
  providers/mysql/v2/plugins/fields/soft_delete_stamp_test.go
  providers/mysql/v2/plugins/fields/soft_delete_test.go
  providers/mysql/v2/plugins/fields/uuid_test.go
  providers/mysql/v2/tx_test.go
Labels: approved

#294 feat(hub): hub print problematic providers for debug
  base/servicehub/hub.go
  base/servicehub/hub_test.go
Labels: approved, feature

#296 fix: func-hook judge `TRACE_HOOK_ENABLE` env
  pkg/trace/inject/hook/hook.go
Labels: approved, bugfix

#297 feat: http-server router-manager support judge started
  providers/httpserver/provider.go
  providers/httpserver/router.go
  providers/httpserver/router_test.go
Labels: feature

#298 fix: redis client maybe nil
  providers/redis/redis.go
Labels: approved, bugfix
