Repository erda-project/erda-infra, pull requests merged in 2022-07, with the labels that each got.

#283 feat: DeletedAtStamp; gorm.v2 provider
  go.mod
  providers/mysql/v2/mysql.go
  providers/mysql/v2/option.go
  providers/mysql/v2/plugins/fields/soft_delete.go
  providers/mysql/v2/plugins/fields/soft_delete_stamp.go
  providers/mysql/v2/plugins/fields/soft_delete_stamp_test.go
  providers/mysql/v2/plugins/fields/soft_delete_test.go
  providers/mysql/v2/tx.go
  providers/mysql/v2/tx_test.go
Labels: feature

#285 feat: record http-server error to log
  providers/httpserver/server/server.go
Labels: feature

#286 feat: add useful middlewares for httpserver
  providers/httpserver/interceptors/bodydump.go
  providers/httpserver/interceptors/log.go
  providers/httpserver/interceptors/requestid.go
  providers/httpserver/provider.go
  providers/httpserver/server/server.go
Labels: feature

#288 feat(httpserver): enhance middlewares
  providers/httpserver/examples/simple/examples.yaml
  providers/httpserver/interceptors/bodydump.go
  providers/httpserver/interceptors/cors.go
  providers/httpserver/interceptors/interceptor.go
  providers/httpserver/interceptors/interceptor_test.go
  providers/httpserver/interceptors/log.go
  providers/httpserver/interceptors/recover.go
  providers/httpserver/interceptors/requestid.go
  providers/httpserver/provider.go
Labels: approved, feature

#289 feat: httpserver add PassThroughDebugFlag middleware for proxy
  providers/httpserver/interceptors/interceptor.go
  providers/httpserver/interceptors/interceptor_test.go
  providers/httpserver/mock/httpresponsewriter.go
  providers/httpserver/provider.go
Labels: approved, feature

#290 specify required lowest go version is 1.17 in go.mod
  go.mod
  tools/go.mod
Labels: approved
