Repository erda-project/erda-infra, pull requests merged in 2024-03, with the labels that each got.

#314 chore: replace xormplus => xorm
  go.mod
  go.sum
  providers/mysqlxorm/examples/main.go
  providers/mysqlxorm/session.go
  providers/mysqlxorm/sqlite3/interface.go
  providers/mysqlxorm/sqlite3/interface_test.go
  providers/mysqlxorm/sqlite3/provider.go
  providers/mysqlxorm/xorm.go
Labels: approved

#315 fix: upgrade clickhouse-go version for fix acquire conn timeout
  go.mod
  go.sum
Labels: approved, bugfix

#316 feat: sqlite journal mode
  go.mod
  go.sum
  providers/mysqlxorm/sqlite3/examples/examples.yaml
  providers/mysqlxorm/sqlite3/examples/main.go
  providers/mysqlxorm/sqlite3/interface.go
  providers/mysqlxorm/sqlite3/interface_test.go
  providers/mysqlxorm/sqlite3/options.go
  providers/mysqlxorm/sqlite3/provider.go
Labels: approved

#317 feat: add xorm closeState and sqlite's randomName
  providers/mysqlxorm/sqlite3/examples/examples.yaml
  providers/mysqlxorm/sqlite3/examples/main.go
  providers/mysqlxorm/sqlite3/interface.go
  providers/mysqlxorm/sqlite3/interface_test.go
  providers/mysqlxorm/sqlite3/options.go
  providers/mysqlxorm/sqlite3/provider.go
  providers/mysqlxorm/xorm.go
Labels: approved, feature

#318 chore: upgrade routine version
  go.mod
  go.sum
  pkg/trace/inject/context/context.go
Labels: approved
